project:
  type: website

website:
  title: ""
  navbar:
    logo: /images/pip_logo.png
    logo-href: https://pip.worldbank.org
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        text: Source Data
        href: https://github.com/GPID-WB/pip-chartbook.git
  page-footer:
    left: "Â© 2025 Poverty & Inequality Platform"
    right: "[![](/images/wbg_logo.png){height=30px}](https://www.worldbank.org)"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid:
      body-width: 950px
      margin-width: 180px

execute:
  python: false

